<?php
namespace Thom2503\PhpUnicodeAnalyzer;

/**
 * Rules to specify what functions have what kind of string kinds as either arguments or return types.
 *
 * Conventions:
 *   arg    => the kind this function expects its primary string argument to be
 *   return => the kind this function produces as output
 *
 * StringKind::BINARY  — byte-level operation, encoding-unsafe
 * StringKind::UNICODE — encoding-aware, safe for multibyte text
 *
 * @property array $rules - private array of rules to determine the kinds for several functions
 * @method ?array get(string $name) - search for a name in the $rules to get the StringKind.
 */
class FunctionRules {
	private array $rules = [
		'strlen'         => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strpos'         => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'stripos'        => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strrpos'        => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'substr'         => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'substr_count'   => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'substr_replace' => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strstr'         => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'stristr'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strrchr'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strtolower'     => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strtoupper'     => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'ucfirst'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'ucwords'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'lcfirst'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'str_replace'    => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'str_ireplace'   => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strtr'          => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'str_pad'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'str_split'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strcmp'         => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strncmp'        => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strcasecmp'     => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strncasecmp'    => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strnatcmp'      => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strnatcasecmp'  => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strcoll'        => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strspn'         => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strcspn'        => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'strpbrk'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strtok'         => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'strrev'         => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'str_word_count' => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'wordwrap'       => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'printf'         => ['arg' => StringKind::BINARY],
		'vprintf'        => ['arg' => StringKind::BINARY],
		'vsprintf'       => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'fprintf'        => ['arg' => StringKind::BINARY],
		'vfprintf'       => ['arg' => StringKind::BINARY],
		'ord'            => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'chr'            => ['arg' => StringKind::MIXED,   'return' => StringKind::BINARY],
		'trim'           => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'ltrim'          => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'rtrim'          => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'preg_match'              => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'preg_match_all'          => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'preg_replace'            => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'preg_replace_callback'   => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'preg_replace_callback_array' => ['arg' => StringKind::BINARY, 'return' => StringKind::BINARY],
		'preg_split'              => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'preg_filter'             => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'preg_grep'               => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'mb_strlen'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'mb_strpos'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'mb_stripos'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'mb_strrpos'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'mb_substr'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_substr_count'  => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'mb_strstr'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_stristr'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_strtolower'    => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_strtoupper'    => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_ucfirst'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_lcfirst'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_str_pad'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_str_split'     => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_trim'          => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_ltrim'         => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_rtrim'         => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_ord'           => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'mb_chr'           => ['arg' => StringKind::MIXED,   'return' => StringKind::UNICODE],
		'mb_convert_case'  => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'mb_convert_encoding' => ['arg' => StringKind::BINARY, 'return' => StringKind::UNICODE],
		'mb_detect_encoding'  => ['arg' => StringKind::BINARY, 'return' => StringKind::MIXED],
		'mb_internal_encoding' => ['return' => StringKind::MIXED],
		'Byte::len'          => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::pos'          => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::ipos'         => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::rpos'         => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::substr'       => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::substr_count' => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::replace'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::ireplace'     => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::tolower'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::toupper'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::trim'         => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::ltrim'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::rtrim'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::ucfirst'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::ucwords'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::pad'          => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::split'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::strstr'       => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::stristr'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::strrev'       => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::strncmp'      => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::strcasecmp'   => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::strncasecmp'  => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::substr_replace' => ['arg' => StringKind::BINARY, 'return' => StringKind::BINARY],
		'Byte::strcspn'      => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::strspn'       => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::strpbrk'      => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::ord'          => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::chr'          => ['arg' => StringKind::MIXED,   'return' => StringKind::BINARY],
		'Byte::pmatch'       => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Byte::preplace'     => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::psplit'       => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'Byte::pmatchall'    => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'Str::len'           => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::pos'           => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::ipos'          => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::rpos'          => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::substr'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::replace'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::ireplace'      => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::tolower'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::toupper'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::trim'          => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::ltrim'         => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::rtrim'         => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::ucfirst'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::ucwords'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::pad'           => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::split'         => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::startswith'    => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::endswith'      => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::contains'      => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::substr_count'  => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::substr_replace' => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::strrev'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::strcmp'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::casecmp'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::ncmp'          => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::ncasecmp'      => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::ord'           => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::chr'           => ['arg' => StringKind::MIXED,   'return' => StringKind::UNICODE],
		'Str::sprintf'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::pmatch'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::pmatchall'     => ['arg' => StringKind::UNICODE, 'return' => StringKind::MIXED],
		'Str::preplace'      => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::preplacecallback' => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::psplit'        => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::pgrep'         => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'Str::pfilter'       => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'file_get_contents'  => ['return' => StringKind::BINARY],
		'fread'              => ['return' => StringKind::BINARY],
		'stream_get_contents' => ['return' => StringKind::BINARY],
		'base64_decode'      => ['return' => StringKind::BINARY],
		'gzdecode'           => ['return' => StringKind::BINARY],
		'gzinflate'          => ['return' => StringKind::BINARY],
		'hex2bin'            => ['return' => StringKind::BINARY],
		'pack'               => ['return' => StringKind::BINARY],
		'json_encode'        => ['return' => StringKind::UNICODE],
		'json_decode'        => ['return' => StringKind::UNICODE],
		'htmlspecialchars'   => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'htmlentities'       => ['arg' => StringKind::BINARY,  'return' => StringKind::MIXED],
		'html_entity_decode' => ['return' => StringKind::UNICODE],
		'nl2br'              => ['arg' => StringKind::UNICODE, 'return' => StringKind::UNICODE],
		'number_format'      => ['return' => StringKind::MIXED],
		'sprintf'            => ['return' => StringKind::BINARY],
		'date'               => ['return' => StringKind::MIXED],
		'md5'                => ['return' => StringKind::MIXED],
		'sha1'               => ['return' => StringKind::MIXED],
		'bin2hex'            => ['return' => StringKind::MIXED],
		'base64_encode'      => ['return' => StringKind::MIXED],
		'urlencode'          => ['return' => StringKind::MIXED],
		'urldecode'          => ['return' => StringKind::UNICODE],
		'rawurlencode'       => ['return' => StringKind::MIXED],
		'rawurldecode'       => ['return' => StringKind::UNICODE],
		'http_build_query'   => ['return' => StringKind::MIXED],
		'implode'            => ['return' => StringKind::BINARY],
		'join'               => ['return' => StringKind::BINARY],
		'explode'            => ['arg' => StringKind::BINARY],
		'str_repeat'         => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'chunk_split'        => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
		'wordwrap'           => ['arg' => StringKind::BINARY,  'return' => StringKind::BINARY],
	];

	public function get(string $name): ?array {
		return $this->rules[strtolower($name)] ?? null;
	}
}